
if(DEFINED ENV{BUILD_VER})
  set(PROJECT_VERSION $ENV{BUILD_VER})
else()
  set(PROJECT_VERSION 9.9.9)
endif()

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(THREADS_PREFER_PTHREAD_FLAG ON)

option(BUILD_TESTS "Build Test Cases" OFF)
